#!/system/bin/sh
# Software desenvolvido por Trevias Xk
# Redes sociais:       treviasxk
# Github:              https://github.com/treviasxk

cmd=$1
export bin=/system/bin
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD
localbuild="/data/local/ubuntu"

banner (){
    clear
    echo " ============= UBUNTU TERMUX ROOT ============="
    echo -e "\e[1m\e[32m ______  ___  ___ _    _ .   _   ___   _  _ _ _"
    echo "   ||   |__/ |___  \  /  |  /_\  |__    \/  |/ "
    echo "   ||   |  \ |___   \/   | /   \  __|  _/\_ |\_"
    echo -e "\e[0m\e[39m ______________________________________________"
    echo " REDES SOCIAIS:                       treviasxk"
    echo " VERSÃO:                              1.0.2.0"
    echo " LICENÇA:                             GPL-3.0"
    echo " =============================================="
}

suuninstall (){
  banner
  echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALANDO UBUNTU... \e[0m"
  mount -o rw,remount /data 2> /dev/null
  mount -o rw,remount /system/bin 2> /dev/null
  rm /system/bin/ubuntu 2> /dev/null
  rm $PREFIX/bin/ubuntu 2> /dev/null
  rm -rf $localbuild 2> /dev/null
  echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALAÇÃO CONCLUÍDO! \e[0m"
  exit
}

uninstall (){
  banner
  echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALANDO UBUNTU... \e[0m"
  sudo mount -o rw,remount /data 2> /dev/null
  sudo mount -o rw,remount /system/bin 2> /dev/null
  sudo rm /system/bin/ubuntu 2> /dev/null
  rm $PREFIX/bin/ubuntu 2> /dev/null
  sudo rm -rf $localbuild 2> /dev/null
  echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALAÇÃO CONCLUÍDO! \e[0m"
  exit
}


if [ "$EUID" -ne 0 ]
then
  case $cmd in
    "")
      #vazio
    ;;
    "-u")
      suuninstall
    ;;
    "--uninstall")
      suuninstall
    ;;
    *)
      echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m COMANDO INVÁLIDO! \e[0m"
      exit
    ;;
  esac
  setenforce 0
  mount -o remount,suid /data
  mountpoint -q $localbuild/dev
  mount -o bind /dev $localbuild/dev
  mount -t devpts devpts $localbuild/dev/pts
  mount -t proc proc $localbuild/proc
  mount -t sysfs sysfs $localbuild/sys
  mount -t tmpfs none $localbuild/tmp
  chmod 666 /dev/null
  #sysctl -w net.ipv4.ip_forward=1

  clear
  chroot $localbuild /bin/login -f root
else
  case $cmd in
    "")
      #vazio
    ;;
    "-u")
      uninstall
    ;;
    "--uninstall")
      uninstall
    ;;
    *)
      echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m COMANDO INVÁLIDO! \e[0m"
      exit
    ;;
  esac
  sudo setenforce 0
  sudo mount -o remount,suid /data
  sudo mountpoint -q $localbuild/dev
  sudo mount -o bind /dev $localbuild/dev
  sudo mount -t devpts devpts $localbuild/dev/pts
  sudo mount -t proc proc $localbuild/proc
  sudo mount -t sysfs sysfs $localbuild/sys
  sudo mount -t tmpfs none $localbuild/tmp
  sudo chmod 666 /dev/null
  #sudo sysctl -w net.ipv4.ip_forward=1

  clear
  sudo chroot $localbuild /bin/login -f root
fi