#!/system/bin/sh
cmd=$1
export bin=/system/bin
export PATH=/usr/bin:/usr/sbin:/bin:/usr/local/bin:/usr/local/sbin:$PATH
export TERM=linux
export HOME=/root
export USER=root
export LOGNAME=root
unset LD_PRELOAD

suuninstall (){
  if [ "$cmd" -ne 0 ]
  then
    banner
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALANDO UBUNTU... \e[0m"
    rm /system/bin/ubuntu
    rm /data/data/com.termux/files/usr/bin/ubuntu
    rm -rf /data/local/ubuntu
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALAÇÃO CONCLUÍDO! \e[0m"
    exit
  fi
}

uninstall (){
  if [ "$cmd" -ne 0 ]
  then
    banner
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALANDO UBUNTU... \e[0m"
    sudo rm /system/bin/ubuntu
    sudo rm /data/data/com.termux/files/usr/bin/ubuntu
    sudo rm -rf /data/local/ubuntu
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m DESINSTALAÇÃO CONCLUÍDO! \e[0m"
    exit
  fi
}

case $cmd in
  "-u")
    suuninstall
  ;;
  "--uninstall")
    suuninstall
  ;;
  *)
    echo -e "\e[30;48;5;82m STATUS \e[40;38;5;82m Comando válido! \e[0m"
  ;;
esac

if [ "$EUID" -ne 0 ]
then
  setenforce 0
  mount -o remount,suid /data
  mountpoint -q /data/local/ubuntu/dev
  mount -o bind /dev /data/local/ubuntu/dev
  mount -t devpts devpts /data/local/ubuntu/dev/pts
  mount -t proc proc /data/local/ubuntu/proc
  mount -t sysfs sysfs /data/local/ubuntu/sys
  mount -t tmpfs none /data/local/ubuntu/tmp
  chmod 666 /dev/null
  sysctl -w net.ipv4.ip_forward=1

  clear
  chroot /data/local/ubuntu /bin/login -f root
else
  sudo setenforce 0
  sudo mount -o remount,suid /data
  sudo mountpoint -q /data/local/ubuntu/dev
  sudo mount -o bind /dev /data/local/ubuntu/dev
  sudo mount -t devpts devpts /data/local/ubuntu/dev/pts
  sudo mount -t proc proc /data/local/ubuntu/proc
  sudo mount -t sysfs sysfs /data/local/ubuntu/sys
  sudo mount -t tmpfs none /data/local/ubuntu/tmp
  sudo chmod 666 /dev/null
  sudo sysctl -w net.ipv4.ip_forward=1

  clear
  sudo chroot /data/local/ubuntu /bin/login -f root
fi